/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonUi {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ParagraphUi {
    }
}
declare global {
    interface HTMLButtonUiElement extends Components.ButtonUi, HTMLStencilElement {
    }
    var HTMLButtonUiElement: {
        prototype: HTMLButtonUiElement;
        new (): HTMLButtonUiElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLParagraphUiElement extends Components.ParagraphUi, HTMLStencilElement {
    }
    var HTMLParagraphUiElement: {
        prototype: HTMLParagraphUiElement;
        new (): HTMLParagraphUiElement;
    };
    interface HTMLElementTagNameMap {
        "button-ui": HTMLButtonUiElement;
        "my-component": HTMLMyComponentElement;
        "paragraph-ui": HTMLParagraphUiElement;
    }
}
declare namespace LocalJSX {
    interface ButtonUi {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ParagraphUi {
    }
    interface IntrinsicElements {
        "button-ui": ButtonUi;
        "my-component": MyComponent;
        "paragraph-ui": ParagraphUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-ui": LocalJSX.ButtonUi & JSXBase.HTMLAttributes<HTMLButtonUiElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "paragraph-ui": LocalJSX.ParagraphUi & JSXBase.HTMLAttributes<HTMLParagraphUiElement>;
        }
    }
}
